### ISSUE TITLE
Issue: General task view improvements

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/WebTechnologies#477]
**Format:** The task view has already been partially converted to the new Markdown-based format but there are still quite a few glitches. Many packages are still listed with (broken) CRAN or GitHub links rather than using the `pkg()` or `github()` tags. Also the explicit list of CRAN packages should be removed. See the [corresponding documentation](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) for more details.

**Update:** This would also be a good time to check the entire task whether it is up to date and correct. A write-up of the general goals and content guidelines is now summarized in the workflow for [proposing new task views](https://github.com/cran-task-views/ctv/blob/main/Proposal.md). Improving your task view to conform more closely with these goals and guidelines, if necessary, would be highly appreciated.

**Co-maintainers:** In particular, we strongly encourage that all task views not only have a principal maintainer but also 1-5 co-maintainers in order to get more inspirations for extensions/improvements and share the maintenance workload. So please try to extend the list of co-maintainers, ideally also including female contributors and generally involving persons with diverse backgrounds.

**Comment by pachadotdev** [comment]
the format was fixed in #479 :100:

**Comment by zeileis** [comment]
Thanks a lot, much appreciated! But not quite 💯 yet. I fixed numerous broken URLs, replaced Omegahat and Google Code links with `ohat()` and `gcode()` tags respectively, standardized the `### Links` section (handled specially in `ctv`), replaced the outdated instructions on how to contribute (using standard phrases from other `ctv` projects), and did various smaller improvements. Please check that everything is in order. In particular, please check that all the GitHub/Omegahat/Google Code links work, e.g., by doing `ctv::ctv2html("WebTechnologies.md")` and then working through the links yourself or with some URL checker.

Also, running `ctv::check_ctv_packages("WebTechnologies.md")` that many of the packages linked with `pkg()` are actually not on CRAN (or not anymore). Please check what the best fixes are for all of these.

**Comment by pachadotdev** [comment]
thanks a lot
I shall present a spreadsheet on google sheets when I feel better, which can be used to keep track of the links

**Comment by zeileis** [comment]
Hi @pachadotdev, did you have any chance to work on the issues listed above? There are still many issues that need to be fixed in the .md file.

Also, did you think about potential co-maintainers? These would be particularly important, if you are not able to address all the issues above at the moment.

**Comment by zeileis** [comment]
Could we please get a follow-up on the questions above? Otherwise we will have to archive the task view on CRAN for now because the current .md file has too many problems.

**Comment by pachadotdev** [comment]
> Could we please get a follow-up on the questions above? Otherwise we will have to archive the task view on CRAN for now because the current .md file has too many problems.

Hi. I'll push what I had from the last weeks, and then I'll push again with the pendings

**Comment by zeileis** [comment]
Thanks, I think this resolves all the important issues, so we can close this issue now.

I would encourage you, though, to keep on thinking about possible co-maintainers who could help with keeping the task view active and up-to-date.
