### ISSUE TITLE
Adding co-maintainer

### ISSUE THREAD

**Issue by pachadotdev** [cran-task-views/WebTechnologies#483]
@wibeasley 

I would love to count you in, you made a great PR to move the view to the current format

**Comment by wibeasley** [comment]
oops, I never responded.  Yes, I'm happy to help maintain it, if you're still interested.  I'm emailing you now, so you have my address and if you want to meet.

**Comment by pachadotdev** [comment]
> oops, I never responded. Yes, I'm happy to help maintain it, if you're still interested. I'm emailing you now, so you have my address and if you want to meet.

amazing!
I shall add you now, I saw the email during the week

**Comment by zeileis** [comment]
Wonderful, welcome on board! I upgrade your role to "Maintain" which we usually use for co-maintainers.
