### ISSUE TITLE
Create GitHub Action to check view on PRs & merges

### ISSUE THREAD

**Issue by wibeasley** [cran-task-views/WebTechnologies#486]
As recommended in https://github.com/cran-task-views/ctv/blob/main/Documentation.md#using-github-actions-to-validate-task-views.

> The GitHub Action can be installed as described in the [action/README](https://github.com/cran-task-views/ctv/blob/main/action/README.md). In its current version, it is automatically run at push or merge requests performed in the main branch of the task view file. More general guidance about [GitHub Actions](https://github.com/features/actions) can be found in the the GitHub documentation.

**Comment by pachadotdev** [comment]
good idea! I do this manually once a month (and with notepad, I'm just implementing VS Code)
