### ISSUE TITLE
lint the markdown?

### ISSUE THREAD

**Issue by wibeasley** [cran-task-views/WebTechnologies#487]
@zeileis  & @pachadotdev, since the views now use standard markdown, do you have an opinion if the md file should meet standard linting recommendations?  For example, here are some cues provided by  a VS Code extension.  Stuff line line wrapping and headings.

![image](https://user-images.githubusercontent.com/1372890/215305320-ede0d464-acb6-4ec4-9822-8b147dc2ea25.png)

**Comment by zeileis** [comment]
Linting is not a requirement in the CRAN Task View Initiative. Of course, the maintainers of the individual task views can decide to lint their task views if they wish to do so.

In case you decide to lint your Markdown be sure to avoid line breaks in `r pkg(...)` type code.

**Comment by pachadotdev** [comment]
> @zeileis & @pachadotdev, since the views now use standard markdown, do you have an opinion if the md file should meet standard linting recommendations? For example, here are some cues provided by a VS Code extension. Stuff line line wrapping and headings.
> 
> ![image](https://user-images.githubusercontent.com/1372890/215305320-ede0d464-acb6-4ec4-9822-8b147dc2ea25.png)

Excellent recommendation.  I did some manual linting with notepad ~1 yr ago, it would be extremely positive to check it again with the changes since then.

**Comment by wibeasley** [comment]
nuts, I made these changes to the main branch.  I'll fix it tomorrow (and allow #485 to merge w/o conflict).

**Comment by wibeasley** [comment]
nuts, I made these changes to the main branch.  I'll fix it tomorrow (and allow #485 to merge w/o conflict).
