### ISSUE TITLE
routine to check urls in a task view

### ISSUE THREAD

**Issue by wibeasley** [cran-task-views/WebTechnologies#493]
_Originally posted by @zeileis in https://github.com/cran-task-views/WebTechnologies/issues/492#issuecomment-1414522690_
            
We currently do not have support for this in the package. The reason is that most URLs are autogenerated by the task views and then there is typically only a rather short list of additional links at the end.

Of course, the WebTechnologies task view is different here. One possible way to check this would be to use the functionality from the basic `tools` package (leveraging `curl` behind the scenes). It's relatively easy to use albeit unexported, unfortunately.

The first step is to construct a URL "database", simply a `data.frame` with additional class `url_db`, containing the `URL` and information about the `Parent` document where this is listed. Subsequently, this database can then be checked. For example:

```
db <- tools:::url_db_from_installed_packages("ctv")
head(db, 3)
##                                       URL          Parent
## 1 https://github.com/cran-task-views/ctv/ ctv/DESCRIPTION
## 2      https://ctv.R-Forge.R-project.org/ ctv/DESCRIPTION
## 3   https://CRAN.R-project.org/doc/Rnews/    ctv/CITATION
tools:::check_url_db(db)
```

So you could write a function `url_db_from_ctv_md()` or something along those lines

**Comment by wibeasley** [comment]
@zeileis, we have a routine that I think will work well for our task view.  Thanks for routing us to `tools:::check_url_db()` which does all the hard work.

Tell us if you want it incorporated into the ctv package, and we'll reduce the dependencies on non-core packages like [rematch2](https://cran.r-project.org/package=rematch2).

Although it may take a minute for me to remember how to use [R-Forge](https://r-forge.r-project.org/scm/viewvc.php/pkg/R/ctv-client.R?view=markup&root=ctv).  I used it a lot 10+ years ago.

https://github.com/cran-task-views/WebTechnologies/blob/main/scripts/url-db-from-ctv-md.R

**Comment by zeileis** [comment]
Thanks! I'll raise it with Kurt (Hornik) and also ask him whether he might export `check_url_db()` in future versions.
