### ISSUE TITLE
standardized R setup instructions?

### ISSUE THREAD

**Issue by pachadotdev** [cran-task-views/WebTechnologies#514]
not web technologies per se, but CRAN official instructions for Fedora instructions tell you how to link install.packages to the system's package manager

we can do the same for Ubuntu but I could not find centralized documentation, therefore I made this https://github.com/pachadotdev/r-packages-ubuntu including a PPA to be able to run `apt install rstudio` on Ubuntu as one would run `dnf install rstudio`  on Fedora.

what do you think @zeileis ?

**Comment by zeileis** [comment]
@eddelbuettel knows much more about this and I hope he can provide some feedback.

**Comment by pachadotdev** [comment]
> @eddelbuettel knows much more about this and I hope he can provide some feedback.

Thanks. I'll see what they say at rOpenSci
