### ISSUE TITLE
Package 'RStripe' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/WebTechnologies#521]
Package [RStripe](https://CRAN.R-project.org/package=RStripe) is currently listed in CRAN Task View [WebTechnologies](https://CRAN.R-project.org/view=WebTechnologies) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by pachadotdev** [comment]
find a way to contact the author, the email on DESCRIPTION is not active

**Comment by wibeasley** [comment]
Looks like the username on the GitHub repo isn't active either (or something not click-able): <https://github.com/AnalyticalFlavorSystems/RStripe>.

All the repos in the org are archived too <https://github.com/AnalyticalFlavorSystems>.

I'm comfortable if you want to say the package is dead (the last commit was 8 years ago). 
 But if they owe you money or something, their org links to this web page: <https://www.gastrograph.com/>.

**Comment by wibeasley** [comment]
closed w/ 2122653454c80c4992515b7654b95f8819a5413e
