### ISSUE TITLE
Package 'transcribeR' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/WebTechnologies#522]
Package [transcribeR](https://CRAN.R-project.org/package=transcribeR) is currently listed in CRAN Task View [WebTechnologies](https://CRAN.R-project.org/view=WebTechnologies) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by wibeasley** [comment]
@pachadotdev, let's just remove this one.  The package has had only one upload --at that was version 0.0.0, 8 years ago.

https://rdrr.io/cran/transcribeR/

![image](https://github.com/cran-task-views/WebTechnologies/assets/1372890/d2e66d7b-0469-4403-8a6c-712f4b47916e)
