### ISSUE TITLE
Package 'XML2R' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/WebTechnologies#528]
Package [XML2R](https://CRAN.R-project.org/package=XML2R) is currently listed in CRAN Task View [WebTechnologies](https://CRAN.R-project.org/view=WebTechnologies) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by wibeasley** [comment]
note to ourselves:
* <https://github.com/cpsievert/XML2R> is the correct url.  (But <http://cpsievert.github.com/XML2R> is listed in the archived description from the old GitHub convention.)
* Though the package hasn't had a commit in 10 years, it looks like [Carson](https://github.com/cpsievert) is still very active in the world of R packages.  So [I asked him](https://github.com/cpsievert/XML2R/issues/10) if there's another package that should replace it.

cc: @pachadotdev

**Comment by cpsievert** [comment]
I never received notice of this since I don't have access to that email (`sievert@iastate.edu`) anymore 🤦  

@kurthornik any chance you'd be able to forward messages from CRAN about it's archival? Check results don't indicate any issues. I'm also not sure how I'd change the address since I don't have access to the old one.

**Comment by zeileis** [comment]
My reading of the XML2R page on CRAN <https://CRAN.R-project.org/package=XML2R> is that the bouncing maintainer e-mail address was the problem. Maybe Kurt @kurthornik can provide further details if there are any.

When re-submitting the package to CRAN, you can follow the advice from the [CRAN policy](https://CRAN.R-project.org/web/packages/policies.html):

> Explain any change in the maintainer’s email address and if possible send confirmation from the previous address (by a separate email to CRAN-submissions@R-project.org) or explain why it is not possible.

**Comment by kurthornik** [comment]
>>>>> Achim Zeileis writes:

> My reading of the XML2R page on CRAN
> https://CRAN.R-project.org/package=XML2R is that the bouncing
> maintainer e-mail address was the problem. Maybe Kurt @kurthornik can
> provide further details if there are any.

Indeed, email to the maintainer address had bounced.

Best
-k

**Comment by pachadotdev** [comment]
> I never received notice of this since I don't have access to that email (`sievert@iastate.edu`) anymore 🤦
> 
> @kurthornik any chance you'd be able to forward messages from CRAN about it's archival? Check results don't indicate any issues. I'm also not sure how I'd change the address since I don't have access to the old one.

Now I see why my emails bounced. Ok, how can we help to put it back on CRAN?

**Comment by cpsievert** [comment]
XML2R is back on CRAN now, thanks everyone
